In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import files

In [ ]:
files.upload()

Saving User_Data.csv to User_Data.csv


{'User_Data.csv': b'User ID,Age,EstimatedSalary,Purchased\r\n15624510,19,19000,0\r\n15810944,35,20000,0\r\n15668575,26,43000,0\r\n15603246,27,57000,0\r\n15804002,19,76000,0\r\n15728773,27,58000,0\r\n15598044,27,84000,0\r\n15694829,32,150000,1\r\n15600575,25,33000,0\r\n15727311,35,65000,0\r\n15570769,26,80000,0\r\n15606274,26,52000,0\r\n15746139,20,86000,0\r\n15704987,32,18000,0\r\n15628972,18,82000,0\r\n15697686,29,80000,0\r\n15733883,47,25000,1\r\n15617482,45,26000,1\r\n15704583,46,28000,1\r\n15621083,48,29000,1\r\n15649487,45,22000,1\r\n15736760,47,49000,1\r\n15714658,48,41000,1\r\n15599081,45,22000,1\r\n15705113,46,23000,1\r\n15631159,47,20000,1\r\n15792818,49,28000,1\r\n15633531,47,30000,1\r\n15744529,29,43000,0\r\n15669656,31,18000,0\r\n15581198,31,74000,0\r\n15729054,27,137000,1\r\n15573452,21,16000,0\r\n15776733,28,44000,0\r\n15724858,27,90000,0\r\n15713144,35,27000,0\r\n15690188,33,28000,0\r\n15689425,30,49000,0\r\n15671766,26,72000,0\r\n15782806,27,31000,0\r\n15764419,27,17000

In [ ]:
user=pd.read_csv('User_Data.csv')
user


User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]

In [ ]:
x=user.iloc[:,[1,2]].values
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
y=user['Purchased']

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
xtrain=sc_x.fit_transform(xtrain)
xtest=sc_x.transform(xtest)

In [ ]:
xtrain

array([[ 0.94054638, -1.385055  ],
       [ 0.06755306, -0.52330683],
       [ 1.23154416, -1.385055  ],
       [ 0.55254935,  1.74596334],
       [ 0.35855083,  0.30971639],
       [ 0.55254935,  1.86086309],
       [ 0.45555009,  0.33844133],
       [-0.5144425 , -1.44250488],
       [-0.12644546,  0.88421517],
       [ 0.06755306,  0.07991688],
       [-0.32044398,  1.34381419],
       [-1.48443509,  0.36716627],
       [-0.90243953,  1.57361371],
       [-1.6784336 ,  0.39589121],
       [-0.22344472,  0.30971639],
       [ 0.45555009,  0.33844133],
       [-0.22344472, -1.32760512],
       [-0.90243953, -1.04035573],
       [-0.80544027,  0.42461615],
       [-0.5144425 , -1.44250488],
       [-0.5144425 ,  1.40126407],
       [-0.22344472,  1.14273962],
       [-1.09643805,  0.33844133],
       [-0.22344472,  0.07991688],
       [ 0.26155157, -0.32223226],
       [-0.70844102, -1.47122982],
       [ 2.00753823,  2.17683742],
       [-0.99943879, -1.385055  ],
       [-0.12644546,

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier= LogisticRegression()
classifier.fit(xtrain,ytrain)
ypred=classifier.predict(xtest)

In [ ]:
ypred

array([1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(ytest,ypred)
cm

array([[76,  6],
       [ 8, 30]])

In [ ]:
from sklearn.metrics import accuracy_score
ac=accuracy_score(ytest,ypred)
ac

0.8833333333333333

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(ytest,ypred)

0.8581514762516047